on:
  schedule:
    - cron: "*/5 1-5 * * 1-5"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4  # 修正依賴包名稱

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python test1.py  # 確保 test1.py 位於正確路徑
